### ISSUE TITLE
Custom Hotkey?

### ISSUE THREAD

**Issue by HillsCloud** [ArminGh02/google-from-everywhere#2]
Awesome utility that saves a bunch of time. 

Quick question though: Is there any way to assign a custom hotkey like CTRL+2 or CTRL+3?

**Comment by ArminGh02** [comment]
> Awesome utility that saves a bunch of time.  

I'm really glad to hear that.

> Quick question though: Is there any way to assign a custom hotkey like CTRL+2 or CTRL+3?  

I think best way to achieve this would be to install AutoHotKey yourself and then modify the [source code](https://github.com/ArminGh02/google-from-everywhere/blob/master/GoogleFromEverywhere.ahk) and recompile it.


You should only care about the following lines:
```ahk
#+g::GoogleSelection()

#+w::DefineSelection()
```

Assigning ctrl+2 to the googling functionality and ctrl+3 to the defining functionality the modified version would be:
```ahk
^2::GoogleSelection()

^3::DefineSelection()
```

Let me know if you needed any further help or you are not comfortable with this approach.

**Comment by HillsCloud** [comment]
ArminGh02, thank you so much for your prompt feedback!!! Unfortunately, I am not a developer but will try to dabble and see if I can do it!
